### ISSUE TITLE
How to overwrite existing relations?

### ISSUE THREAD

**Issue by marcovtwout** [yiiext/with-related-behavior#16]
Hello,

I use this extension to link model User to Group like this:

``` php
// set groups
// $this->groupList contains Group id's
$groups = array();
foreach($this->groupList as $id) {
    $group = MailerGroup::model()->findByPk($id);
    if ($group === null)
        throw new CException('Invalid MailerGroup->id in submitted list');
    $groups[] = $group;
}
$this->groups = $groups;
// save with related
return $this->withRelated->save(false, array('groups' => array('id')));
```

Can I use the behavior to delete existing user-group-links first?
Or do I have to do that manually before saving?

**Comment by creocoder** [comment]
This is custom update strategy, so you should do it in User::beforeSave(). I'll later document this in readme.

**Comment by marcovtwout** [comment]
You might want to use this as an example in the readme:

``` php
Yii::app()->db->createCommand()->delete('User_Group', 'userId = ?', array($this->id));
```

Maybe you can use my use case in the starter post as an example how to use -existing- models with this behavior? It's also not documented.

**Comment by Narretz** [comment]
So you actually retrieve your related models, then delete the linking table entries, and then let the withRelated save them again, with changes or additional related models?

I hoped there would be an easier way for stuff like this ...

**Comment by marcovtwout** [comment]
Me too.. :)

**Comment by manuel-84** [comment]
Please @creocoder update the Documentation with an example and provide also a better explation of the first parameter of the save() function, that is always "true" (runValidation) because it's not clear from start

**Comment by creocoder** [comment]
> better explation of the first parameter of the save() function

You can check this extension API from its comments. First parameter of WithRelatedBehavior::save() method same as CActiveRecord::save() method. Both do not need any special explaination.

> update the Documentation with an example

There is some plans to implement WithRelatedBehavior::link() and WithRelatedBehavior::unlink() method. Since its not implemented this extension should be used only for saving main model and its related models (not deleting, not linking and not unlinking, etc). When this methods will be ready then documentation will be updated.
