### ISSUE TITLE
what about delete?

### ISSUE THREAD

**Issue by cebe** [yiiext/with-related-behavior#7]
Would be nice to have a remove/delete option to delete related objects or even disconnect the relation.
Not sure whats the best way to do this right now...

**Comment by creocoder** [comment]
This relation is for insert/update main model record and insert/update its related models. There is no best way to delete related objects for all situations. I can show how to do this for a concrete example. Disconnect/connect makes sense only for MANY_MANY relation types and it will be. We need more research in order to implement this is an optimal way.

**Comment by cebe** [comment]
You are right. Since I was using this extension for MANY_MANY only, I did not think of that.

**Comment by creocoder** [comment]
Ok, i close ticket for now, disconnect/connect for MANY_MANY already in todo.

**Comment by cebe** [comment]
would be nice to see todo somewhere open, so people could comment on things before they get coded and might add usefull ideas.

github issues is a quite usefull tool for managing todolist. example: https://github.com/cebe/code-dashboard/issues
